---
- name: Copy a file to rpi hosts
  hosts: rpis
  serial: 0  # Run tasks in parallel for all hosts
  gather_facts: no
  pre_tasks:
    - name: Gather Facts
      include_tasks: gather_facts.yaml
  tasks:
    - name: Ensure client directory exists
      ansible.builtin.file:
        path: /home/pi/client
        state: directory
        mode: "0755"

    - name: Copy files
      ansible.builtin.copy:
        src: src/client/
        dest: /home/pi/client/
        recursive: yes

- name: Copy file to server
  hosts: server
  tasks:
    - name: Copy the server file
      copy:
        src: src/server
        dest: /home/techtile/server
        directory_mode: yes
