---
- name: Check and install uhd
  hosts: rpis
  become: yes
  serial: 0  # Run tasks in parallel for all hosts
  gather_facts: no
  pre_tasks:
    - name: Gather Facts
      include_tasks: gather_facts.yaml
  tasks:
    - name: Update apt package cache
      ansible.builtin.apt: 
        update_cache: yes
    - name: Upgrade all packages
      ansible.builtin.apt: 
        upgrade: yes
    - name: Install Lib uhd
      apt:
        name: libuhd-dev
        state: present
        force_apt_get: yes
        update_cache: yes
    - name: Install uhd host
      apt:
        name:  uhd-host
        state: present
        force_apt_get: yes
        update_cache: yes
      become: yes
    - name: Install uhd images
      ansible.builtin.shell:
        cmd: "uhd_images_downloader"
       become: yes
       tags:
        - install_uhd_images
    - name: Install uhd Python
      apt:
        name:  python3-uhd
        state: present
        force_apt_get: yes
        update_cache: yes
      become: yes
    - name: Export neccessary paths
      lineinfile:
        path: "~/.profile"
        line: "{{ item }}"
      loop:
        - 'export PATH=/home/pi/.local/bin:$PATH'
        - 'export PYTHONPATH=/usr/local/lib/python3/dist-packages'
        - 'export LD_LIBRARY_PATH=/usr/local/lib'
        #- 'export UHD_IMAGES_DIR=/usr/local/share/uhd/images'
    - name: Configure USB
      ansible.builtin.shell: 
        cmd: | 
          cp uhd-usrp.rules /etc/udev/rules.d/ &&
          udevadm control --reload-rules && 
          udevadm trigger 
        chdir: "/home/pi/uhd/host/utils"
      become: yes
      become_method: sudo

