---
- name: Kill Python script
  hosts: "{{ tiles }}"
  gather_facts: no
  pre_tasks:
    - name: Gather Facts
      include_tasks: gather_facts.yaml
  tasks:
    - name: Kill the background script process
      #command: pkill -f tx_waveforms.py
      command: pkill -f tx_waveforms_random_phase.py
      ignore_errors: yes
