---
- name: Copy files and load image
  hosts: "{{ tiles }}"
  serial: 0  # Run tasks in parallel for all hosts
  gather_facts: no
  # pre_tasks:
  #   - name: Gather Facts
  #     include_tasks: gather_facts.yaml
  tasks:
    - name: Ensure exp directory exists
      ansible.builtin.file:
        path: /home/pi/repos/usrp
        state: directory
        mode: "0755"
    - name: Clone the repository
      git:
        repo: "https://github.com/techtile-by-dramco/usrp"
        dest: "/home/pi/repos/usrp"
        version: "main"  # or specify a branch, tag, or commit hash

    - name: Find devices usrp
      ansible.builtin.shell:
        cmd: "uhd_find_devices"
        chdir: /home/pi/repos/usrp/fpga
        executable: /bin/bash

    - name: Load image in usrp
      ansible.builtin.shell:
        cmd: "uhd_image_loader --args='type=b200' --no-fw --fpga-path='./usrp_b210_fpga.bin'"
        chdir: /home/pi/repos/usrp/fpga
        executable: /bin/bash
