---
- name: Check and install uhd
  hosts: rpis
  become: yes
  serial: 0 # Run tasks in parallel for all hosts
  gather_facts: no
  pre_tasks:
    - name: Gather Facts
      include_tasks: gather_facts.yaml
  tasks:
    - name: Run command in shell
      ansible.builtin.shell:
        cmd: "{{ cmd }}"
# usage: ansible-playbook -i inventory/hosts.yaml -l rpis run_cmd.yaml -e "cmd=<your cmd>"
