---
- name: Check and install uhd
  hosts: rpis
  serial: 0 # Run tasks in parallel for all hosts
  gather_facts: no
  pre_tasks:
    - name: Gather Facts
      include_tasks: gather_facts.yaml
  tasks:
    - name: Run command in shell
      ansible.builtin.shell:
        cmd: "{{ cmd }}"
        chdir: /home/pi/client
        executable: /bin/bash
      register: command_output
    - name: Display command output
      ansible.builtin.debug:
        var: command_output.stdout_lines
# usage: ansible-playbook -i inventory/hosts.yaml -l rpis run_cmd.yaml -e "cmd='<your cmd>'"
