---
- name: Check and install uhd
  hosts: "{{ tiles }}"
  environment:
    PYTHONPATH: "/usr/local/lib/python3/dist-packages"
    UHD_IMAGES_DIR: "/usr/share/uhd/images" # no idea why we need to include this as it is defined .bashrc
  tasks:
    - name: Execute transmitter script in the background
      ansible.builtin.shell:
        # cmd: "nohup python3 tx_waveforms_random_phase.py -w const -f {{ freq }} -c {{ channels }} --wave-freq 0  --gain {{ gain }} --wave-ampl 1.0 -d {{ duration }} --ip {{ ip }}> log.txt 2>&1 &"
        cmd: "nohup python3 {{ script }} -f {{ freq }} -c {{ channels }} --gain {{ gain }} -d {{ duration }} --ip {{ ip }} > log.txt 2>&1 &"
        cmd: "nohup python3 {{ script }} --config {{ ansible_hostname }} > log.txt 2>&1 &"
        # voorlaatste versie cmd: "nohup python3 tx_waveforms_random_phase_v2.py -w const -f {{ freq }} -c {{ channels }} --wave-freq 0  --gain {{ gain }} --wave-ampl 1.0 -d {{ duration }} --ip {{ ip }} > log.txt 2>&1 &"
        # cmd: "nohup python3 rpi_client.py > log.txt 2>&1 &"
        # cmd: "python3 rpi_client.py --port {{ port }} --channels {{ channels }} --rate {{ rate }} --freq {{ freq }} --gain {{ gain }}"
        chdir: /home/pi/client
        executable: /bin/bash
