---
- name: Check and install uhd
  hosts: rpis
  become: true  # Run the command with sudo privileges
  serial: 0 # Run tasks in parallel for all hosts
  gather_facts: no
  pre_tasks:
    - name: Gather Facts
      include_tasks: gather_facts.yaml
  tasks:
    - name: Reload bashrc
      command: source ~/.bashrc
    - name: Execute receiver script in the background
      ansible.builtin.shell:
        cmd: "nohup python3 tx_waveforms.py -w const -f 910E6 -c 0 1 --wave-freq 0  --gain 100 -d 6"
        # cmd: "nohup python3 rpi_client.py > log.txt 2>&1 &"
        # cmd: "python3 rpi_client.py --port {{ port }} --channels {{ channels }} --rate {{ rate }} --freq {{ freq }} --gain {{ gain }}"
        chdir: /home/pi/client
        executable: /bin/bash
    - name: Display command output
      ansible.builtin.debug:
        var: command_output.stdout_lines
# usage: ansible-playbook -i inventory/hosts.yaml -l rpis run_cmd.yaml -e "cmd='<your cmd>'"
