- name: Ansible recipe to ping remote hosts
  hosts: "{{ tiles }}"
  gather_facts: no
  pre_tasks: 
  - name: Gather Facts
    include_tasks: gather_facts.yaml

  tasks:
  - name: Ping
    action: ping
  - name: Clean up exp directory for every client
    file:
      path: /home/pi/exp
      state: absent
