---
- name: Set global Git user email
  ansible.builtin.command:
    cmd: git config --global user.email "dramco.research@gmail.com"

- name: Set global Git user name
  ansible.builtin.command:
    cmd: git config --global user.name "techtile-by-dramco"

- name: Set uhd directory
  set_fact:
    uhd_repo_dir: "/home/pi/uhd"

- name: Clone the uhd repository
  git:
    repo: https://github.com/EttusResearch/uhd.git
    dest: "{{ uhd_repo_dir }}"
    clone: yes
    update: yes
    force: true
     
- name: Checkout uhd to version v4.7
  command:
    chdir: "{{ uhd_repo_dir }}"
    cmd: git checkout UHD-4.7

- name: Download iface.patch file
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/techtile-by-dramco/raspberrypi-uhd/refs/heads/master/iface.patch
    dest: /home/pi/uhd/iface.patch

- name: Apply patch using git apply 
  ansible.builtin.command:
    cmd: git apply /home/pi/uhd/iface.patch
    chdir: "{{ uhd_repo_dir }}"

- name: Clone the volk repository
  git:
    repo: https://github.com/gnuradio/volk.git
    dest: "/home/pi/volk"
    clone: yes
    update: yes
    recursive: yes

- name: Set volk directory
  set_fact:
    volk_repo_dir: "/home/pi/volk"
