---
- name: Create a build directory
  ansible.builtin.file:
    path: /home/pi/volk/build
    state: directory

- name: Set volk build directory
  set_fact: 
    volk_build_dir: "/home/pi/volk/build" 

- name: Run cmake, make and test
  ansible.builtin.shell: 
    cmd: |
      cmake -DCMAKE_BUILD_TYPE=Release ../ &&
      make -j6 &&
      make test
    chdir: "{{ volk_build_dir }}"

- name: Run make install and idconfig
  ansible.builtin.shell: 
    cmd: |
      make install &&
      ldconfig
    chdir: "{{ volk_build_dir }}"
  become: yes
  become_method: sudo