---
- name: Update, upgrade and install apt packages
  become: yes  
  block:
    - name: Run apt update with allow-releaseinfo-change
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Run apt upgrade
      ansible.builtin.apt:
        upgrade: yes
        dpkg_options: 'force-confold'
      environment:
        DEBIAN_FRONTEND: noninteractive
        UCF_FORCE_CONFFOLD: 1
      become: yes
      become_method: sudo
    
    - name: Install required packages
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: present
        force_apt_get: yes
        update_cache: yes
        dpkg_options: 'force-confold'
      environment:
        DEBIAN_FRONTEND: noninteractive
        UCF_FORCE_CONFFOLD: 1
      become: yes
      become_method: sudo

- name: Create a build directory
  ansible.builtin.file:
    path: /home/pi/uhd/host/build
    state: directory
  
- name: Mark build directory
  set_fact: 
    uhd_build_dir: "/home/pi/uhd/host/build"

- name: Run cmake, make and test
  ansible.builtin.shell: 
    cmd: |
      cmake -DCMAKE_INSTALL_PREFIX=/usr/local ../ -DENABLE_C_API=O -DENABLE_PYTHON_API=ON -DENABLE_LIBUHD=ON -DENABLE_PYMOD_UTILS=ON -DENABLE_B100=OFF -DENABLE_USRP1=OFF -DENABLE_USRP2=OFF -DENABLE_X300=OFF -DENABLE_N300=OFF  -DENABLE_N320=OFF -DENABLE_E300=OFF -DENABLE_E320=OFF -DENABLE_X400=OFF -DUHD_LOG_MIN_LEVEL=1 &&
      make -j6 &&
      make test
    chdir: "{{ uhd_build_dir }}"

- name: Copy UHD files to Python 3 dist-packages directory
  ansible.builtin.command:
    cmd: cp -a /usr/local/lib/python3.7/site-packages/uhd/. /usr/local/lib/python3/dist-packages/uhd/
  become: yes
  become_method: sudo

- name: Run install, idconfig and images loader
  ansible.builtin.shell: 
    cmd: | 
      make -j6 install &&
      ldconfig && 
      uhd_images_downloader 
    chdir: "{{ uhd_build_dir }}"
  become: yes
  become_method: sudo

- name: Configure USB
  ansible.builtin.shell: 
    cmd: | 
      cp uhd-usrp.rules /etc/udev/rules.d/ &&
      udevadm control --reload-rules && 
      udevadm trigger 
    chdir: "/home/pi/uhd/host/utils"
  become: yes
  become_method: sudo

- name: Validate if UHD installed correctely
  ansible.builtin.shell: 
    cmd: uhd_usrp_probe
  
