---
- name: Copy a file to rpi hosts
  hosts: "{{ tiles }}"
  serial: 0  # Run tasks in parallel for all hosts
  gather_facts: no
  pre_tasks:
    - name: Gather Facts
      include_tasks: gather_facts.yaml
  tasks:
    - name: Copy files
      ansible.builtin.copy:
        src: src/client/pll/
        dest: /home/pi/
        #recursive: yes
