---
- name: Check and install uhd
  hosts: "{{ tiles }}"
  gather_facts: no
  serial: 0 # Run tasks in parallel for all hosts
  strategy: free # run all tasks per node parralel, instead of the default run task parallel and then move to the next
  vars_files:
    - install_uhd/packages.yaml
  pre_tasks:
    - name: Gather Facts
      include_tasks: gather_facts.yaml
  tasks:
  - name: Check if uhd are installed
    include_tasks: install_uhd/check-uhd.yaml

  - name: Get all repositories
    include_tasks: install_uhd/get-source.yaml
    # when: not uhd_exists

  - name: Build if UHD are not installed
    include_tasks: install_uhd/install-uhd.yaml
    # when: not uhd_exists

  - name: Build volk
    include_tasks: install_uhd/install-volk.yaml
    # when: not uhd_exists

  - name: Install pybind11 and pyzmq
    ansible.builtin.pip:
      name: 
        - pybind11
        - pyzmq
      state: present
      executable: pip3

  # - name: Install GNURadio
  #   apt:
  #     name: gnuradio
  #     state: present
  #     force_apt_get: yes
  #     update_cache: yes
  #   become: yes

  - name: Export neccessary paths
    lineinfile:
      path: "~/.bashrc"
      line: "{{ item }}"
    loop:
      - 'export PATH=/home/pi/.local/bin:$PATH'
      # - 'export PYTHONPATH=/usr/local/lib/python3/dist-packages'
      - 'export LD_LIBRARY_PATH=/usr/local/lib'

  - name: Clone the experiments repository from GitHub
    git:
      repo: https://github.com/techtile-by-dramco/experiments
      dest: /home/pi/experiments  # Replace with the directory where you want to clone the repository
      force: true
      update: yes
      clone: yes
