---
- name: Ansible recipe to shutdown remote host 
  hosts: "{{ tiles }}"
  ignore_unreachable: yes
  become: yes
  become_method: sudo

  - name: "Shutdown"
    block:
    - name: "Shutdown after {{ timeout_seconds | string }} seconds"
      community.general.shutdown:
        delay: "{{ timeout_seconds }}"
        msg: "Shutting down machine in {{ timeout_seconds | string }} seconds"
      when: timeout_seconds != 0
    - name: "Shutdown immediately"
      community.general.shutdown:

      when: timeout_seconds == 0

    when: action_to_take == "shutdown"

  - name: "Reboot"
    block:
    - name: "Reboot after {{ timeout_seconds | string }} seconds and wait until back up"
      ansible.builtin.reboot:
        pre_reboot_delay: "{{ timeout_seconds }}"
        msg: "Rebooting machine in {{ timeout_seconds | string }} seconds"
      when: timeout_seconds != 0
    - name: "Reboot immediately and wait until back online"
      ansible.builtin.reboot:

      when: timeout_seconds == 0

    when: action_to_take == "reboot"